### PR TITLE
Add Affine Cipher

### PR DESCRIPTION
**Pull request by sibasish14**
Add python program to implement Affine Cipher
Closes https://github.com/palash25/pyphers/issues/5

### CODE REVIEW

**Comment by sibasish14** [comment]
@palash25 I don't understand...my code worked perfectly when I tested it. 
What's the problem with this `Travis CI` ??? It just always fails!!!
Do I need to follow the `PEP8` guidelines strictly? It's showing too many issues.

**Comment by palash25** [comment]
That's because I haven't set the travis configuration file yet because I'm lazy. So just ignore travis and do what PEP8 asks.

**Comment by palash25** [comment]
Yes you need to follow PEP8 the whole point of this event is to get you guys ready for contributing to real organization with much more stringent rules. Try writing a linter bear for coala then you will know what I mean :wink:

**Comment by sibasish14** [comment]
Ah, it's all so difficult....
I'll get back to work though ;)

**Comment by sibasish14** [comment]
@palash25 what does it mean by `indentation contains tab` ?

**Comment by sibasish14** [comment]
@palash25 please check now, Did my best though.

**Comment by sibasish14** [comment]
Thanks for correcting my errors @palash25 .
Will keep that in mind from now on.

**Pull request merged**
