### PR TITLE
Add Vigenere Cipher

### PR DESCRIPTION
**Pull request by sibasish14**
Python implementation of Vigenere Cipher.

### CODE REVIEW

**Comment by palash25** [comment]
@sibasish14 This looks good. Just one change though you should remove your name from the file as I think its redundant. If someone opens this file github will automatically show you as the author of this commit so there is no need to write the author's name. Amend your commit and I will merge it.

**Comment by palash25** [comment]
Also can you update the README.md accordingly

**Comment by palash25** [comment]
The README change should be a separate commit and should be made after you have amended the previous one and pushed along with this PR. So in the end you will have 2 commits in this PR.

**Comment by sibasish14** [comment]
What changes should I make in the README.md file?
Include the GeeksforGeeks link for the cipher?(It's in cpp though)

**Comment by palash25** [comment]
Yeah you can include that link if you want.

**Comment by sibasish14** [comment]
Changes done. Please have a look.

**Comment by palash25** [comment]
@sibasish14 good work :+1:

**Comment by palash25** [comment]
update the spreadsheet

**Comment by sibasish14** [comment]
Should I delete my current branch or keep it for further commits(if any)?

**Comment by palash25** [comment]
@sibasish14 Yes delete it on your fork and also on your clone every PR need a new branch so since your PR has been merged you don't need this branch anymore. Just keep your fork and clone updated by pulling from upstream.

**Comment by sibasish14** [comment]
For updating my clone its - git pull ??

**Comment by palash25** [comment]
google it or refer to coala's guide

**Pull request merged**
