### PR TITLE
updated playfair cipher code 

### PR DESCRIPTION
**Pull request by debck**

### CODE REVIEW

**Review by sibasish14 — CHANGES_REQUESTED** [review]
@debck Make necessary changes as mentioned by @pep8speaks ;)

**Comment by debck** [comment]
@sibasish14 kk

**Review by sibasish14 — CHANGES_REQUESTED** [review]
@debck Did you run this code locally?
Because I don't see any indentation in your code, so there's a high probability that you might encounter errors while running it. And the checks are failing for the same reason I suppose ;)

**Comment by palash25** [comment]
@debck there is no way that this code is going to run python is very sensitive about indentation.

**Comment by debck** [comment]
@palash25  Ok then ...I am closing this PR now ...will  check again then push it

**Comment by palash25** [comment]
@debck  dont close PR's without asking you could push again to the same PR after making your changes.  Next time keep that in mind.

**Comment by debck** [comment]
plz check the code again. Did my best

**Review by sibasish14 — CHANGES_REQUESTED** [review]
@debck  you need to follow the PEP8 guidlines strictly.
Refer to this https://www.python.org/dev/peps/pep-0008/

**Comment by debck** [comment]
i updated it and its showing only one failing check ie.travis CI

**Comment by sibasish14** [comment]
@debck do not close a PR unless you're asked to do so.

**Comment by sibasish14** [comment]
Travis CI build will always fail because it has not been updated. Just ignore it and make sure you follow the pep8 guidelines.

**Pull request closed without merging**
